# Generated by Django 2.0.3 on 2018-04-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180403_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='副标题'),
        ),
    ]
