# Generated by Django 2.0.3 on 2018-04-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_banner_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='DocumentIntro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='文档介绍'),
        ),
        migrations.AlterField(
            model_name='service',
            name='ServiceIntro',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='服务介绍'),
        ),
    ]
