# Generated by Django 2.0.3 on 2018-04-05 10:43

import datetime
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180403_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SupportId', models.CharField(max_length=10, verbose_name='支持ID')),
                ('SupportName', models.CharField(max_length=30, verbose_name='支持名称')),
                ('SupportIntro', models.TextField(blank=True, null=True, verbose_name='支持介绍')),
                ('SupportImage', models.ImageField(upload_to=users.models.image_directory_path_support, verbose_name='支持图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '支持',
                'verbose_name_plural': '支持',
            },
        ),
    ]
