# Generated by Django 2.0.3 on 2018-04-11 15:05

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180407_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='SupportImage',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.image_directory_path_support, verbose_name='支持图片'),
        ),
    ]
