# Generated by Django 2.0.3 on 2018-04-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180411_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='FirmCity',
            field=models.CharField(max_length=50, null=True, verbose_name='公司城市'),
        ),
        migrations.AddField(
            model_name='firm',
            name='FirmCountry',
            field=models.CharField(max_length=50, null=True, verbose_name='所属国家'),
        ),
    ]
